spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blackmarket?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: 3579

mybatis:
  mapper-locations: mapper/**/*.xml


